### PR TITLE
how to add team members #27

### LINKED ISSUE #27: Process for adding members to teams for maintainers
Yesterday I had lunch with my friend @ysuarez and because I asked him to help me do some research for https://github.com/good-labs/slopi-communication/issues/2 I thought I'd give him credit and visibility by creating a "slopi-read" team at https://github.com/orgs/good-labs/teams/slopi-read/members and co-assigning him to that issue. Creating the team was not a problem but now I'm blocked adding him to the team. The "Invite" button is not clickable for me. Here's a screenshot:

Screen Shot 2019-05-25 at 6 48 51 AM

Let's document what people who start projects under good-labs need to do to invite people to join GitHub teams associated with their projects. I'm open to suggestions of where to document this. Perhaps a future version of https://good-labs.github.io/contributing/ ?

The audience for this documentation is "maintainers" to use GitHub's terms. Here's a screenshot showing that I'm a maintainer:

Screen Shot 2019-05-25 at 6 59 32 AM

### PR DESCRIPTION
**Pull request by pdurbin**
Closes #27

Copied from CONTRIBUTING.md from https://github.com/good-labs/.github

The content was added in https://github.com/good-labs/.github/pull/2

### CODE REVIEW

**Comment by vsoch** [comment]
Why do we want the redundancy? Wouldn't it make sense to maintain in one spot, and then reference the docs there?

**Comment by pdurbin** [comment]
@vsoch it might be easier if you make a pull request for how you envision this. I'm pretty confused.

**Comment by vsoch** [comment]
No worries I can help to explain. We have one file, and it's in the .github folder. We do this so we don't need to update *two* places with changes. Then in the README here if you want to reference it, say something like "For governance, including adding team members, joining the Good Labs, and other community information, please see [our Contributing documentation](https://www.github.com/good-labs/.github)

And you can adjust the list to how you see appropriate, and link directly to files if you think that's appropriate too.

So here is what you do for this PR:
 - add this note to the README
 - delete the CONTRIBUTING.md file here
 - if the .github CONTRIBUTING.md is missing information from the one here, put it there.

**Comment by pdurbin** [comment]
@vsoch ok, I just made pull request #30 and I'm closing this one if favor of the new one.

**Pull request closed without merging**
